// Edit this file to add projects and photos.
// Put your images into /img/<project-id>/ and list them here.
// Tip: if images don't refresh online, rename files (01_v2.jpg) to beat browser cache.

const PROJECTS = [
  {
    id: "seton-townhomes",
    title: "Seton Townhomes",
    location: "Calgary, AB",
    cover: "img/seton-townhomes/01.jpg",
    photos: [
      "img/seton-townhomes/01.jpg",
      "img/seton-townhomes/9.jpg",
      "img/seton-townhomes/2.jpg",
      "img/seton-townhomes/3.jpg",
      "img/seton-townhomes/4.jpg",
      "img/seton-townhomes/5.jpg",
      "img/seton-townhomes/6.jpg",
      "img/seton-townhomes/7.jpg",
      "img/seton-townhomes/8.jpg",
      "img/seton-townhomes/10.jpg",
      "img/seton-townhomes/11.jpg",
      "img/seton-townhomes/12.jpg",
      "img/seton-townhomes/13.jpg",
      "img/seton-townhomes/14.jpg",
      "img/seton-townhomes/15.jpg",
      "img/seton-townhomes/16.jpg",
      "img/seton-townhomes/17.jpg",
      "img/seton-townhomes/18.jpg",
      "img/seton-townhomes/19.jpg",
      "img/seton-townhomes/20.jpg",
      "img/seton-townhomes/21.jpg",
      "img/seton-townhomes/22.jpg",
      "img/seton-townhomes/23.jpg",
      "img/seton-townhomes/24.jpg",
      "img/seton-townhomes/25.jpg",
      "img/seton-townhomes/26.jpg",
      "img/seton-townhomes/27.jpg",
      "img/seton-townhomes/28.jpg",
      "img/seton-townhomes/29.jpg",
      "img/seton-townhomes/30.jpg",
      "img/seton-townhomes/31.jpg",
      "img/seton-townhomes/32.jpg",
      "img/seton-townhomes/33.jpg",
      "img/seton-townhomes/34.jpg",
      "img/seton-townhomes/35.jpg",
      "img/seton-townhomes/36.jpg",
      "img/seton-townhomes/37.jpg",
      "img/seton-townhomes/38.jpg"
    ]
  },
  {
    id: "commercial-plaza",
    title: "Commercial Plaza (Metal Cladding, Hardie® & Lux Siding)",
    location: "Calgary, AB",
    cover: "img/commercial-plaza/01.jpg",
    photos: [
      "img/commercial-plaza/01.jpg",
      "img/commercial-plaza/02.jpg",
      "img/commercial-plaza/03.jpg",
      "img/commercial-plaza/04.jpg",
      "img/commercial-plaza/05.jpg",
      "img/commercial-plaza/06.jpg",
      "img/commercial-plaza/07.jpg",
      "img/commercial-plaza/08.jpg",
      "img/commercial-plaza/09.jpg",
      "img/commercial-plaza/10.jpg",
      "img/commercial-plaza/11.jpg",
      "img/commercial-plaza/12.jpg",
      "img/commercial-plaza/13.jpg",
      "img/commercial-plaza/14.jpg"
    ]
  },
  {
    id: "single-family",
    title: "Residential Homes (Single-Family & Multi-Family)",
    location: "Calgary, AB",
    cover: "img/single-family/01.jpg",
    photos: [
      "img/single-family/01.jpg",
      "img/single-family/2.jpg",
      "img/single-family/3.jpg",
      "img/single-family/4.jpg",
      "img/single-family/5.jpg",
      "img/single-family/6.jpg",
      "img/single-family/7.jpg",
      "img/single-family/8.jpg",
      "img/single-family/9.jpg",
      "img/single-family/10.jpg",
      "img/single-family/11.jpg",
      "img/single-family/12.jpg",
      "img/single-family/13.jpg",
      "img/single-family/14.jpg",
      "img/single-family/16.jpg",
      "img/single-family/17.jpg",
      "img/single-family/18.jpg",
      "img/single-family/19.jpg",
      "img/single-family/20.jpg",
      "img/single-family/21.jpg",
      "img/single-family/22.jpg",
      "img/single-family/23.jpg"
    ]
  },
  {
  id: "parkdale",
  title: "Parkdale (hardie panels with Z-bar and easy tream system)",
  cover: "img/parkdale/01.jpg",
  photos: [
    "img/parkdale/01.jpg",
    "img/parkdale/02.jpg",
    "img/parkdale/03.jpg"
  ]
},
{
  id: "bow-33",
  title: "Bow 33 (hardie panel, hardie plank and lux soffit)",
  cover: "img/bow-33/01.jpg",
  photos: [
    "img/bow-33/01.jpg",
    "img/bow-33/2.jpg",
    "img/bow-33/3.jpg",
    "img/bow-33/4.jpg",
    "img/bow-33/5.jpg",
    "img/bow-33/6.jpg",
    "img/bow-33/7.jpg",
    "img/bow-33/8.jpg",
    "img/bow-33/9.jpg",
    "img/bow-33/10.jpg",
    "img/bow-33/11.jpg",
    "img/bow-33/12.jpg",
    "img/bow-33/13.jpg",
    "img/bow-33/14.jpg",
    "img/bow-33/15.jpg",
    "img/bow-33/16.jpg",
    "img/bow-33/17.jpg",
    "img/bow-33/18.jpg",
    "img/bow-33/19.jpg",
    "img/bow-33/20.jpg",
    "img/bow-33/21.jpg"
  ]
},
{
  id: "carrington",
  title: "Carrington (fuul hardie)",
  cover: "img/carrington/01.jpg",
  photos: [
    "img/carrington/01.jpg",
    "img/carrington/2.jpg",
    "img/carrington/3.jpg",
    "img/carrington/4.jpg",
    "img/carrington/5.jpg",
    "img/carrington/6.jpg",
    "img/carrington/7.jpg",
    "img/carrington/8.jpg",
    "img/carrington/9.jpg",
    "img/carrington/10.jpg",
    "img/carrington/11.jpg",
    "img/carrington/12.jpg",
    "img/carrington/13.jpg",
    "img/carrington/14.jpg",
    "img/carrington/15.jpg",
    "img/carrington/16.jpg",
    "img/carrington/17.jpg",
    "img/carrington/18.jpg",
    "img/carrington/19.jpg",
    "img/carrington/20.jpg",
    "img/carrington/21.jpg",
    "img/carrington/22.jpg",
    "img/carrington/23.jpg",
    "img/carrington/24.jpg",
    "img/carrington/25.jpg",
    "img/carrington/26.jpg",
    "img/carrington/27.jpg",
    "img/carrington/28.jpg",
    "img/carrington/29.jpg",
    "img/carrington/30.jpg",
    "img/carrington/31.jpg",
    "img/carrington/32.jpg",
    "img/carrington/33.jpg",
    "img/carrington/34.jpg",
    "img/carrington/35.jpg",
    "img/carrington/36.jpg",
    "img/carrington/37.jpg",
    "img/carrington/37.jpg",
    "img/carrington/39.jpg",
    "img/carrington/40.jpg",
    "img/carrington/41.jpg",
    "img/carrington/42.jpg"
  ]
},
{
  id: "adelaide",
  title: "Adelaide (board&button, hardie panels with Z-bar and easy tream)",
  cover: "img/adelaide/01.jpg",
  photos: [
    "img/adelaide/01.jpg",
    "img/adelaide/2.jpg",
    "img/adelaide/3.jpg",
    "img/adelaide/4.jpg",
    "img/adelaide/5.jpg",
    "img/adelaide/6.jpg",
    "img/adelaide/7.jpg",
    "img/adelaide/8.jpg",
    "img/adelaide/9.jpg",
    "img/adelaide/10.jpg",
    "img/adelaide/11.jpg",
    "img/adelaide/12.jpg",
    "img/adelaide/13.jpg",
    "img/adelaide/14.jpg",
    "img/adelaide/15.jpg",
    "img/adelaide/16.jpg",
    "img/adelaide/17.jpg",
    "img/adelaide/18.jpg",
    "img/adelaide/19.jpg",
    "img/adelaide/20.jpg",
    "img/adelaide/21.jpg",
    "img/adelaide/22.jpg",
    "img/adelaide/23.jpg",
    "img/adelaide/24.jpg",
    "img/adelaide/25.jpg",
    "img/adelaide/26.jpg",
    "img/adelaide/27.jpg",
    "img/adelaide/28.jpg",
    "img/adelaide/29.jpg",
    "img/adelaide/30.jpg",
    "img/adelaide/31.jpg",
    "img/adelaide/32.jpg",
    "img/adelaide/33.jpg",
    "img/adelaide/34.jpg",
    "img/adelaide/35.jpg",
    "img/adelaide/36.jpg",
    "img/adelaide/37.jpg",
    "img/adelaide/38.jpg",
    "img/adelaide/39.jpg",
    "img/adelaide/40.jpg",
    "img/adelaide/41.jpg",
    "img/adelaide/42.jpg",
    "img/adelaide/43.jpg",
    "img/adelaide/44.jpg",
    "img/adelaide/45.jpg",
    "img/adelaide/46.jpg",
    "img/adelaide/47.jpg",
    "img/adelaide/48.jpg",
    "img/adelaide/49.jpg",
    "img/adelaide/50.jpg",
    "img/adelaide/51.jpg"
  ]
},


  
];
